services:
  api_gateway:
    build: ../dinner_managment_api_gateway
    stdin_open: true
    tty: true
    volumes:
      - ../dinner_managment_api_gateway/src:/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - LOCAL_HOST=0.0.0.0
      - HTTP_PORT=8000
      - ZMQ_SERVER_HOST=0.0.0.0
      - BUSINESS_LOGIC_HOST=business_logic
      - BUSINESS_LOGIC_PORT=8001
    ports: 
     - 8000:8000
    command: /bin/sh -c "python main.py"

  business_logic:
    build: ../dinner_managment_business_logic
    stdin_open: true
    tty: true
    volumes:
      - ../dinner_managment_business_logic/src:/src
    environment:
      - LOCAL_HOST=0.0.0.0
      - DATABASE_GATEWAY_HOST=database_gateway
      - LOCAL_PORT=8001
      - DATABASE_GATEWAY_PORT=8002
    ports:
     - 8001:8001
    command: /bin/sh -c "python main.py"

  database_gateway:
    build: ../dinner_managment_database_gateway
    stdin_open: true
    tty: true
    volumes:
      - ../dinner_managment_database_gateway/src:/src
    environment:
      - MONGO_URI=mongodb://mongo:27017/dinner_managment_db
      - MONGODB_URL=mongodb://mongo:27017/
      - DATABASE_NAME=justice_db
      - JWT_SECRET=secret_key
      - JWT_ALGORITHM=HS256
      - JWT_EXP_DELTA_SECONDS=3600 
    depends_on:
      - mongo 
    ports:
     - 8002:8002
    command: /bin/sh -c "python main.py"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    attach: false

# ------------------------------------------
# SIMULATORS -------------------------------
# ------------------------------------------
  # client_simulator:
  #   build: ../dinner_managment_client_simulator
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ../dinner_managment_client_simulator/src:/src
# ------------------------------------------
# ------------------------------------------
# ------------------------------------------

volumes:
  mongodata: