services:
  api_gateway:
    build: ../dinner_managment_api_gateway
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - ../dinner_managment_api_gateway/src:/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - LOCAL_HOST=${LOCAL_HOST}
      - HTTP_PORT=${API_GATEWAY_PORT}
      - ZMQ_SERVER_HOST=${LOCAL_HOST}
      - BUSINESS_LOGIC_HOST=business_logic
      - BUSINESS_LOGIC_PORT=${BUSINESS_LOGIC_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_EXP_DELTA_SECONDS=${JWT_EXP_DELTA_SECONDS}
    ports: 
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    # מיפוי יציאת COM3 במחשב Windows לנתיב /dev/ttyS3 בתוך הקונטיינר
    devices:
      - "/dev/ttyS3:/dev/ttyS3"
    command: /bin/sh -c "python main.py"

  business_logic:
    build: ../dinner_managment_business_logic
    stdin_open: true
    tty: true
    volumes:
      - ../dinner_managment_business_logic/src:/src
    environment:
      - LOCAL_HOST=${LOCAL_HOST}
      - DATABASE_GATEWAY_HOST=database_gateway
      - LOCAL_PORT=${BUSINESS_LOGIC_PORT}
      - DATABASE_GATEWAY_PORT=${DATABASE_GATEWAY_PORT}
    ports:
      - "${BUSINESS_LOGIC_PORT}:${BUSINESS_LOGIC_PORT}"
    command: /bin/sh -c "python main.py"

  database_gateway:
    build: ../dinner_managment_database_gateway
    stdin_open: true
    tty: true
    volumes:
      - ../dinner_managment_database_gateway/src:/src
    environment:
      - MONGO_URI=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${DATABASE_NAME}?retryWrites=true&w=majority
      - MONGODB_URL=mongodb://mongo:27017/
      - DATABASE_NAME=${DATABASE_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_EXP_DELTA_SECONDS=${JWT_EXP_DELTA_SECONDS}
      - LOCAL_HOST=${LOCAL_HOST}
      - PORT=${DATABASE_GATEWAY_PORT}
    depends_on:
      - mongo 
    ports:
      - "${DATABASE_GATEWAY_PORT}:${DATABASE_GATEWAY_PORT}"
    command: /bin/sh -c "python main.py"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
